In [11]:
import sys
sys.path.append("..")
from src import index
from src import image_analysis
import numpy as np
import cv2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [12]:
X1 = index.get_data("../data/processed_images_Potato/Early_Blight","Early_Blight") + index.get_data("../data/processed_images_Potato/Healthy","Healthy") + index.get_data("../data/processed_images_Potato/Late_Blight","Late_Blight")

Y = [x[0] for x in X1]     

In [13]:
features = []
labels   = []
for path, label in X1:
    image = cv2.imread(path)

    if image is None:   
        raise ValueError(f"Image at path {path} could not be loaded.")
    
    hist = image_analysis.get_histogram(image)
    glcm = image_analysis.GLCM(image) 
    combined = np.concatenate([hist, glcm])
    features.append(combined)
    labels.append(label)

X = np.array(features)   # shape (n_images, n_features)
y = np.array(labels)     # shape (n_images,)

print(X.shape, y.shape)

(2152, 184) (2152,)


In [14]:
liste = [10, 23, 35, 42, 59]

for i in range(5):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=liste[i])

    scaler = StandardScaler()

    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test  = scaler.transform(X_test)

    clf = SVC(kernel="rbf")

    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

Early_Blight       0.95      0.98      0.97       200
     Healthy       1.00      0.94      0.97        31
 Late_Blight       0.97      0.95      0.96       200

    accuracy                           0.96       431
   macro avg       0.97      0.96      0.96       431
weighted avg       0.96      0.96      0.96       431

[[196   0   4]
 [  0  29   2]
 [ 10   0 190]]
              precision    recall  f1-score   support

Early_Blight       0.97      0.97      0.97       200
     Healthy       0.97      0.94      0.95        31
 Late_Blight       0.96      0.96      0.96       200

    accuracy                           0.97       431
   macro avg       0.97      0.96      0.96       431
weighted avg       0.97      0.97      0.97       431

[[195   0   5]
 [  0  29   2]
 [  7   1 192]]
              precision    recall  f1-score   support

Early_Blight       0.97      0.96      0.96       200
     Healthy       0.97      0.94    

In [15]:
liste = [10, 23, 35, 42, 59]

for i in range(5):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=liste[i])

    rdm_f = RandomForestClassifier(n_estimators=100, random_state=42)

    rdm_f.fit(X_train, y_train)

    y_pred = rdm_f.predict(X_test)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

Early_Blight       0.96      0.97      0.97       200
     Healthy       1.00      0.87      0.93        31
 Late_Blight       0.95      0.96      0.96       200

    accuracy                           0.96       431
   macro avg       0.97      0.93      0.95       431
weighted avg       0.96      0.96      0.96       431

[[194   0   6]
 [  0  27   4]
 [  8   0 192]]
              precision    recall  f1-score   support

Early_Blight       0.98      0.97      0.98       200
     Healthy       1.00      0.87      0.93        31
 Late_Blight       0.96      0.98      0.97       200

    accuracy                           0.97       431
   macro avg       0.98      0.94      0.96       431
weighted avg       0.97      0.97      0.97       431

[[195   0   5]
 [  0  27   4]
 [  4   0 196]]
              precision    recall  f1-score   support

Early_Blight       0.98      0.96      0.97       200
     Healthy       0.96      0.87    